//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EticaretMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Baskets = new HashSet<Basket>();
            this.Comments = new HashSet<Comment>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.Pictures = new HashSet<Picture>();
        }
    
        public int ID { get; set; }
        public decimal Price { get; set; }
        public int InStock { get; set; }
        public int OnOrder { get; set; }
        public bool IsRecommended { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsSpecial { get; set; }
        public float Discount { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public Nullable<int> Brand_ID { get; set; }
        public Nullable<int> Category_ID { get; set; }
    
        public virtual ICollection<Basket> Baskets { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<Picture> Pictures { get; set; }
    }
}
